version: '3.8'
services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - /etc/localtime:/etc/localtime:ro
    working_dir: /workspace
